Update ViewedProduct.php
getPrice() can be null.

In this case, it causes error:

```
Exception: Deprecated Functionality: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/html/vendor/klaviyo/magento2-extension/Block/Catalog/Product/ViewedProduct.php on line 217
```

We need to convert it to a string before we can use it in`str_replace` as parameter.